<CameraScreen>:
    GridLayout:
        cols: 1
        Camera:
            resolution: (640, 480)
            play: False
            id: camera
        Button:
            text: 'Start Camera'
            on_press: root.start() if root.ids.camera.play == False else root.stop()
            id: camera_button
        Button:
            text: 'Capture'

<RootWidget>:
    CameraScreen:
        id: camera_screen
        name: 'camera_screen'

